### ISSUE TITLE
Ding sound play before game launched

### ISSUE THREAD

**Issue by Z4RM** [iChun/Ding#17]
Hello!
All is in the title. Here is my log :
[latest.log](https://github.com/iChun/Ding/files/8780205/latest.log)
Thank you by advance

**Comment by iChun** [comment]
Do you have mods that changes the Title Screen GUI? Ding listens for when the title screen is set as the screen being shown, which usually happens when Mods have finished loading and the loading bar overlay starts to fade away.

If another mod is setting this earlier than expected, it could make Ding trigger earlier than it should.

NGL Ding really needs to be redone to factor in all these new mods 😂 I'm just trying to figure out why Ding fired early.

**Comment by Z4RM** [comment]
I have Blue Skies that modify the panorama but normally it doesn't affect it, but not another mod that edit the title screen
